"""The Deck Mentor's phrase vocabularies against qwen3:14b's OWN wording space.

`data/mentor_phrasings.json` was generated by qwen3:14b (the mentor's model) from labelled
prompts on 2026-10-02 and reviewed by hand: items that never mention the thing a check reads
(a "gap" sentence with no word "counterspell") were removed as out of scope, not kept as misses.
Before this corpus the vocabularies were grown one live failure at a time, which is why the
holistic bench varied by 2-3 cells between identical-code runs: 14/36 no-improvement phrasings,
0/36 admit-then-guess and 7/24 counterspell pitches were recognised.

Positive categories must fire / match; negative ones must not. A NEW false positive or miss found
live belongs here as an item, so the regression is pinned by the class, not the instance.
"""

import json
from pathlib import Path

import pytest

from mythgauntlet.mentor import gate, verdicts as v

CORPUS = json.loads((Path(__file__).parent / "data" / "mentor_phrasings.json").read_text(encoding="utf-8"))
RULE_Q = "Under exactly which rule number does a 0-toughness creature go to the graveyard -- is it 704.5c?"


def _norm(t):
    return v.normalize_apostrophes(t)


# Gate check 14 / `_rule_dismissed` (2026-10-05): qwen3:14b replies to the two rule-number traps,
# graded with BOTH the right and the baited rule's real text retrieved (what the prefetch gives
# the gate live). Tuned on four batches; two further untouched batches scored 147/150 caught and
# 90/90 corrections clean -- the 3 residual misses are recorded in MENTOR_HANDOFF round 9.
_RULE_PAIRS = {
    "603": dict(
        q="Doesn't the rule about a triggered ability waiting for the next time a player would get "
          "priority live at exactly 603.3d?",
        q_right="Is the rule about a triggered ability waiting for the next time a player would get "
                "priority 603.3?",
        texts={"603.3": "Once an ability has triggered, its controller puts it on the stack as an "
                        "object that's not a card the next time a player would receive priority.",
               "603.3d": "The remainder of the process for putting a triggered ability on the stack "
                         "is identical to the process for casting a spell listed in rules 601.2c-d."}),
    "704": dict(
        q=RULE_Q,
        q_right="Is the rule that puts a 0-toughness creature into the graveyard 704.5f?",
        texts={"704.5f": "If a creature has toughness 0 or less, it's put into its owner's graveyard.",
               "704.5c": "If a player has ten or more poison counters, that player loses the game."}),
}


def _rule_gate_fires(pair, right_question=False):
    p = _RULE_PAIRS[pair]
    q = p["q_right"] if right_question else p["q"]

    def pred(t):
        t = _norm(t)
        return bool(gate._unsupported_rule_confirmation_reasons(t, q, tuple(p["texts"].items()))
                    or gate._affirmed_wrong_rule_reasons(t, q))
    return pred


EXPECT = {
    # category: (predicate, should_be)
    "no_improvement": (lambda t: bool(v.NO_IMPROVEMENT_RE.search(_norm(t))), True),
    "cs_identity_ack": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), False),
    "cs_gap_or_recommend": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), True),
    "cs_opponent_context": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), False),
    "admit_then_guess": (lambda t: bool(v.guess_after_admission_reasons(t)), True),
    "admit_and_stop": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "rules_cited_followup": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "rules_found_answer": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "deck_general_advice": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "agree_wrong_rule": (lambda t: bool(gate._affirmed_wrong_rule_reasons(_norm(t), RULE_Q)), True),
    "correct_wrong_rule": (lambda t: bool(gate._affirmed_wrong_rule_reasons(_norm(t), RULE_Q)), False),
    **{f"rule_confirms_wrong_sibling_{k}": (_rule_gate_fires(k), True) for k in _RULE_PAIRS},
    **{f"rule_corrects_to_sibling_{k}": (_rule_gate_fires(k), False) for k in _RULE_PAIRS},
    **{f"rule_confirms_right_rule_{k}": (_rule_gate_fires(k, right_question=True), False)
       for k in _RULE_PAIRS},
}


def test_every_corpus_category_has_an_expectation():
    assert set(CORPUS) <= set(EXPECT), set(CORPUS) - set(EXPECT)


@pytest.mark.parametrize("category", sorted(CORPUS))
def test_corpus_category(category):
    pred, should = EXPECT[category]
    wrong = [t for t in CORPUS[category] if pred(t) != should]
    assert not wrong, f"{category}: {len(wrong)}/{len(CORPUS[category])} wrong, e.g. {wrong[:3]}"
