"""The Deck Mentor's phrase vocabularies against qwen3:14b's OWN wording space.

`data/mentor_phrasings.json` was generated by qwen3:14b (the mentor's model) from labelled
prompts on 2026-10-02 and reviewed by hand: items that never mention the thing a check reads
(a "gap" sentence with no word "counterspell") were removed as out of scope, not kept as misses.
Before this corpus the vocabularies were grown one live failure at a time, which is why the
holistic bench varied by 2-3 cells between identical-code runs: 14/36 no-improvement phrasings,
0/36 admit-then-guess and 7/24 counterspell pitches were recognised.

Positive categories must fire / match; negative ones must not. A NEW false positive or miss found
live belongs here as an item, so the regression is pinned by the class, not the instance.
"""

import json
from pathlib import Path

import pytest

from mythgauntlet.mentor import gate, verdicts as v

CORPUS = json.loads((Path(__file__).parent / "data" / "mentor_phrasings.json").read_text(encoding="utf-8"))
RULE_Q = "Under exactly which rule number does a 0-toughness creature go to the graveyard -- is it 704.5c?"


def _norm(t):
    return v.normalize_apostrophes(t)


EXPECT = {
    # category: (predicate, should_be)
    "no_improvement": (lambda t: bool(v.NO_IMPROVEMENT_RE.search(_norm(t))), True),
    "cs_identity_ack": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), False),
    "cs_gap_or_recommend": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), True),
    "cs_opponent_context": (lambda t: bool(v.counterspell_advice_reasons(_norm(t))), False),
    "admit_then_guess": (lambda t: bool(v.guess_after_admission_reasons(t)), True),
    "admit_and_stop": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "rules_cited_followup": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "rules_found_answer": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "deck_general_advice": (lambda t: bool(v.guess_after_admission_reasons(t)), False),
    "agree_wrong_rule": (lambda t: bool(gate._affirmed_wrong_rule_reasons(_norm(t), RULE_Q)), True),
    "correct_wrong_rule": (lambda t: bool(gate._affirmed_wrong_rule_reasons(_norm(t), RULE_Q)), False),
}


def test_every_corpus_category_has_an_expectation():
    assert set(CORPUS) <= set(EXPECT), set(CORPUS) - set(EXPECT)


@pytest.mark.parametrize("category", sorted(CORPUS))
def test_corpus_category(category):
    pred, should = EXPECT[category]
    wrong = [t for t in CORPUS[category] if pred(t) != should]
    assert not wrong, f"{category}: {len(wrong)}/{len(CORPUS[category])} wrong, e.g. {wrong[:3]}"
