"""Per-bracket reference distributions for the Power Profile (plan E1 / G10).

"Does this deck do X poorly?" needs a reference point: a Consistency of 60 means nothing
until you know what a typical bracket-3 deck scores. `BRACKET_AXIS_REFERENCE` holds, for each
bracket 1-5 and each metric, the p25/p50/p75 over the labelled corpus decks of that bracket
(the label is the deck builder's own `# bracket: N` claim, see scripts/bracket_accuracy.py).

Regenerate with `python scripts/bracket_axis_reference.py --bake`; detect drift with `--check`.

DIRECTION. `percentile_band` reports where a RAW value sits. For axis scores and `pod`,
higher is better; for `avg_kill_turn` and `avg_commander_turn`, LOWER is better (a deck that
kills on turn 7 is faster than the bracket median of 9, and lands in `below_p25`/`p25_p50`).
The caller interprets direction; this module never says "good" or "bad".
"""

from __future__ import annotations

# Metrics where a smaller number is the better one. Exposed so callers don't hard-code it.
LOWER_IS_BETTER = frozenset({"avg_kill_turn", "avg_commander_turn"})

# === BEGIN GENERATED: BRACKET_AXIS_REFERENCE ===
# Generated by scripts/bracket_axis_reference.py on 2026-09-30: runs=120, 569 labelled decks.
# Do not edit by hand; re-run the script (and `--check` to detect drift).
BRACKET_AXIS_REFERENCE: dict[int, dict[str, dict]] = {1: {'consistency': {'p25': 75.74,
                     'p50': 78.6,
                     'p75': 80.19,
                     'n': 129,
                     'none_count': 0,
                     'thin': False},
     'speed': {'p25': 54.17, 'p50': 82.5, 'p75': 94.17, 'n': 129, 'none_count': 0, 'thin': False},
     'resilience': {'p25': 86.43,
                    'p50': 89.94,
                    'p75': 93.52,
                    'n': 129,
                    'none_count': 0,
                    'thin': False},
     'interaction': {'p25': 33.34,
                     'p50': 57.84,
                     'p75': 77.5,
                     'n': 129,
                     'none_count': 0,
                     'thin': False},
     'ceiling': {'p25': 13.75,
                 'p50': 16.92,
                 'p75': 25.28,
                 'n': 129,
                 'none_count': 0,
                 'thin': False},
     'pod': {'p25': 2.29, 'p50': 14.67, 'p75': 31.22, 'n': 129, 'none_count': 0, 'thin': False},
     'avg_kill_turn': {'p25': 9.55,
                       'p50': 10.15,
                       'p75': 10.8,
                       'n': 121,
                       'none_count': 8,
                       'thin': False},
     'avg_commander_turn': {'p25': 3.84,
                            'p50': 4.74,
                            'p75': 5.75,
                            'n': 126,
                            'none_count': 3,
                            'thin': False}},
 2: {'consistency': {'p25': 77.48,
                     'p50': 79.23,
                     'p75': 80.67,
                     'n': 172,
                     'none_count': 0,
                     'thin': False},
     'speed': {'p25': 80.62, 'p50': 90.83, 'p75': 95.83, 'n': 172, 'none_count': 0, 'thin': False},
     'resilience': {'p25': 85.53,
                    'p50': 88.3,
                    'p75': 91.41,
                    'n': 172,
                    'none_count': 0,
                    'thin': False},
     'interaction': {'p25': 44.04,
                     'p50': 63.39,
                     'p75': 81.42,
                     'n': 172,
                     'none_count': 0,
                     'thin': False},
     'ceiling': {'p25': 15.58,
                 'p50': 19.02,
                 'p75': 26.83,
                 'n': 172,
                 'none_count': 0,
                 'thin': False},
     'pod': {'p25': 9.62, 'p50': 22.0, 'p75': 35.12, 'n': 172, 'none_count': 0, 'thin': False},
     'avg_kill_turn': {'p25': 9.55,
                       'p50': 10.04,
                       'p75': 10.44,
                       'n': 170,
                       'none_count': 2,
                       'thin': False},
     'avg_commander_turn': {'p25': 3.6,
                            'p50': 4.54,
                            'p75': 5.27,
                            'n': 172,
                            'none_count': 0,
                            'thin': False}},
 3: {'consistency': {'p25': 76.82,
                     'p50': 78.31,
                     'p75': 80.17,
                     'n': 147,
                     'none_count': 0,
                     'thin': False},
     'speed': {'p25': 75.83, 'p50': 90.0, 'p75': 95.0, 'n': 147, 'none_count': 0, 'thin': False},
     'resilience': {'p25': 84.86,
                    'p50': 88.05,
                    'p75': 90.92,
                    'n': 147,
                    'none_count': 0,
                    'thin': False},
     'interaction': {'p25': 41.68,
                     'p50': 59.45,
                     'p75': 79.82,
                     'n': 147,
                     'none_count': 0,
                     'thin': False},
     'ceiling': {'p25': 15.03, 'p50': 19.0, 'p75': 24.84, 'n': 147, 'none_count': 0, 'thin': False},
     'pod': {'p25': 7.13, 'p50': 21.8, 'p75': 36.49, 'n': 147, 'none_count': 0, 'thin': False},
     'avg_kill_turn': {'p25': 9.52,
                       'p50': 9.96,
                       'p75': 10.44,
                       'n': 145,
                       'none_count': 2,
                       'thin': False},
     'avg_commander_turn': {'p25': 3.81,
                            'p50': 4.58,
                            'p75': 5.36,
                            'n': 147,
                            'none_count': 0,
                            'thin': False}},
 4: {'consistency': {'p25': 74.24,
                     'p50': 77.1,
                     'p75': 79.7,
                     'n': 66,
                     'none_count': 0,
                     'thin': False},
     'speed': {'p25': 70.62, 'p50': 85.42, 'p75': 93.96, 'n': 66, 'none_count': 0, 'thin': False},
     'resilience': {'p25': 83.6,
                    'p50': 87.31,
                    'p75': 91.8,
                    'n': 66,
                    'none_count': 0,
                    'thin': False},
     'interaction': {'p25': 56.68,
                     'p50': 74.72,
                     'p75': 90.0,
                     'n': 66,
                     'none_count': 0,
                     'thin': False},
     'ceiling': {'p25': 14.95, 'p50': 18.69, 'p75': 26.79, 'n': 66, 'none_count': 0, 'thin': False},
     'pod': {'p25': 5.16, 'p50': 16.96, 'p75': 27.1, 'n': 66, 'none_count': 0, 'thin': False},
     'avg_kill_turn': {'p25': 9.59,
                       'p50': 10.17,
                       'p75': 10.64,
                       'n': 66,
                       'none_count': 0,
                       'thin': False},
     'avg_commander_turn': {'p25': 3.86,
                            'p50': 4.63,
                            'p75': 5.13,
                            'n': 66,
                            'none_count': 0,
                            'thin': False}},
 5: {'consistency': {'p25': 65.46,
                     'p50': 67.87,
                     'p75': 71.08,
                     'n': 55,
                     'none_count': 0,
                     'thin': False},
     'speed': {'p25': 58.75, 'p50': 71.67, 'p75': 87.5, 'n': 55, 'none_count': 0, 'thin': False},
     'resilience': {'p25': 80.05,
                    'p50': 85.4,
                    'p75': 88.51,
                    'n': 55,
                    'none_count': 0,
                    'thin': False},
     'interaction': {'p25': 49.7,
                     'p50': 90.0,
                     'p75': 90.0,
                     'n': 55,
                     'none_count': 0,
                     'thin': False},
     'ceiling': {'p25': 15.2, 'p50': 18.33, 'p75': 36.43, 'n': 55, 'none_count': 0, 'thin': False},
     'pod': {'p25': 1.38, 'p50': 8.25, 'p75': 15.64, 'n': 55, 'none_count': 0, 'thin': False},
     'avg_kill_turn': {'p25': 9.42,
                       'p50': 10.18,
                       'p75': 10.75,
                       'n': 55,
                       'none_count': 0,
                       'thin': False},
     'avg_commander_turn': {'p25': 3.36,
                            'p50': 4.13,
                            'p75': 5.03,
                            'n': 55,
                            'none_count': 0,
                            'thin': False}}}
# === END GENERATED: BRACKET_AXIS_REFERENCE ===



def percentile_band(bracket: int, metric: str, value: float | None,
                    table: dict[int, dict[str, dict]] | None = None) -> dict | None:
    """Where `value` falls in the reference distribution for `bracket`/`metric`.

    Returns None when the value is missing, the cell is unknown, thin (n < 20) or has no
    percentiles -- an honest decline, never a guess. Otherwise
    {"bracket", "p25", "p50", "p75", "n", "percentile_band"} with the band one of
    "below_p25" (< p25), "p25_p50" (p25 <= v < p50), "p50_p75" (p50 <= v < p75),
    "above_p75" (>= p75). The band describes the RAW value; for `LOWER_IS_BETTER` metrics
    "below_p25" is the FAST end.
    """
    if value is None:
        return None
    ref = BRACKET_AXIS_REFERENCE if table is None else table
    cell = ref.get(bracket, {}).get(metric)
    if not cell or cell.get("thin"):
        return None
    p25, p50, p75 = cell.get("p25"), cell.get("p50"), cell.get("p75")
    if p25 is None or p50 is None or p75 is None:
        return None
    if value < p25:
        band = "below_p25"
    elif value < p50:
        band = "p25_p50"
    elif value < p75:
        band = "p50_p75"
    else:
        band = "above_p75"
    return {"bracket": bracket, "p25": p25, "p50": p50, "p75": p75,
            "n": cell["n"], "percentile_band": band}
