"""Everything a swap suggestion is ENTITLED to claim, as structured facts.

`advise` returns "add X, cut Y, +6.9 Ceiling" plus a `reason` string assembled from template
fragments — `"A big dragon your commander can cheat into play; a one-shot team finisher.
Measured: kills ~1.2 turns sooner."` That reads as a list because it is one, and it is silent
on the half a user actually questions: **why THAT card as the cut**. The advisor has known
the answer since `redundancy` landed (the role, how over-supplied it is, how strongly the
card serves it) and never said it.

The fix is a narrative written by a language model. The risk that comes with it is the one
this project cares about most: a fluent sentence is a very good disguise for a fabricated
one, and on an MTG-facing surface a wrong claim about a card is a DEFECT, not an
approximation.

So the generation is split in two, and this module is the first half.

    engine (here)  ->  SwapBrief: the facts, measured, offline, deterministic
    Forge          ->  prose, generated by the local model, then GATED against this brief

**THE BRIEF IS THE CLAIM BUDGET.** It carries everything the narrative may assert, and the
gate rejects anything it cannot trace back here. That is what makes the check mechanical
rather than a matter of taste: `allowed_numbers` and `allowed_card_names` exist precisely so
a verifier can be exact about invention. Nothing here calls a model, reaches the network, or
depends on Forge — the engine stays a measurement authority, and the LLM lives on the side of
the wall that already owns one (`themer` talks to llama-swap; this does not).

The split mirrors the archetype contract: the engine cannot detect themes and is TOLD them,
and the engine cannot write prose and instead says what prose would be allowed to contain.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import asdict, dataclass, field

from mythgauntlet.model.card import Card
from mythgauntlet.model.deck import ResolvedDeck
from mythgauntlet.ratings import redundancy
from mythgauntlet.semantics import tags
from mythgauntlet.semantics.model import EffectVector

# EffectVector field -> the word a reader would use for it. The VALUE side of this mapping is
# the vocabulary a narrative is allowed to use about a card's function, so the gate can ask
# "you called this a counterspell; does the vector agree?" and get a real answer.
#
# Deliberately NOT exhaustive over EffectVector: `impact` is a popularity-seeded prior with no
# meaning to a reader, and `enters_tapped` is a detail no swap rationale turns on. A field
# absent here simply cannot be talked about, which is the safe direction.
FUNCTION_WORDS: dict[str, str] = {
    "ramp_sources": "ramp",
    "fetches_land": "land ramp",
    "draw_cards": "card draw",
    "engine_draw": "repeatable draw",
    "tutor": "tutor",
    "removal": "removal",
    "board_wipe": "board wipe",
    "counterspell": "counterspell",
    "cheats_creatures": "cheats creatures into play",
    "grants_storm": "storm",
    "mana_on_cast": "mana per cast",
    "magecraft_damage": "magecraft burn",
    "cast_damage": "burn per cast",
    "scaling_burn": "scaling burn",
    "spell_cost_reduction": "spell cost reduction",
    "ritual_mana": "ritual mana",
    "overrun_pump": "team pump",
    "overrun_scales": "scaling team pump",
}


def card_functions(ev: EffectVector) -> dict[str, float]:
    """The card's non-empty functions, `{word: magnitude}`.

    A bool becomes 1.0 so the shape is uniform and a verifier never has to branch on type.
    An empty dict means the rung-1 vector cannot read this card at all — which the narrative
    must be able to say honestly rather than guess around.
    """
    out: dict[str, float] = {}
    for attr, word in FUNCTION_WORDS.items():
        value = getattr(ev, attr, None)
        if value:
            out[word] = float(value)
    return out


@dataclass(frozen=True)
class AddBrief:
    """The card being suggested, and why it was even a candidate."""

    name: str
    mana_value: int
    type_line: str
    functions: dict[str, float]
    edhrec_rank: int | None
    on_tribe: str | None = None          # a commander tribe this card's subtypes match
    commander_can_cheat: bool = False    # the commander puts creatures onto the battlefield


@dataclass(frozen=True)
class CutBrief:
    """The card being displaced, and the measured reason it was offered.

    This is the half the template reason never had. `redundancy_backed` is the load-bearing
    field: it is False when the deck over-supplies NO role, in which case `rank_redundant`
    still owed its caller `k` candidates and fell through to its least-played tiebreak. On
    9.0% of corpus decks that is the whole pool (ROADMAP S12). A narrative that calls such a
    cut "redundant" would be inventing the very finding the module failed to produce, so the
    gate refuses it.
    """

    name: str
    mana_value: int
    type_line: str
    functions: dict[str, float]
    edhrec_rank: int | None
    role: str | None                 # the role it is most over-supplied in; None = roleless
    role_supply: float               # what the deck supplies in that role
    role_target: int                 # what decks like this one supply (archetype-adjusted)
    oversupply: float                # supply - target, clamped at 0
    within_role: float               # how strongly this card serves the role
    protected: bool                  # roleless: never redundant
    redundancy_backed: bool          # False -> there was no redundancy to find


@dataclass(frozen=True)
class SwapBrief:
    """One (add, cut) pair, everything measured about it, and its claim budget."""

    axis: str
    axis_label: str
    before: float
    after: float
    delta: float
    noise_floor: float               # the axis's own seed-to-seed spread; delta cleared it
    commander: str | None
    archetypes: list[str]
    add: AddBrief
    cut: CutBrief
    kill_turn_before: float | None = None
    kill_turn_after: float | None = None
    kill_rate_before: float | None = None
    kill_rate_after: float | None = None
    allowed_card_names: list[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return asdict(self)

    @property
    def kill_turn_delta(self) -> float | None:
        """Positive = the swap kills SOONER. None when either side never killed."""
        if self.kill_turn_before is None or self.kill_turn_after is None:
            return None
        return self.kill_turn_before - self.kill_turn_after

    def allowed_numbers(self) -> set[float]:
        """Every number a faithful narrative could cite, for the gate to check against.

        Includes the derived deltas as well as the raw readings, because "1.2 turns sooner"
        is a legitimate sentence and the subtraction happens in prose. Mana values and role
        counts are here for the same reason.

        This is deliberately GENEROUS — it is an anti-fabrication check, not a style rule.
        Its job is to catch a model that invented "cuts your curve by 4 points" out of
        nothing, not to police which of the true numbers a sentence chose to use.
        """
        nums: set[float] = {
            round(self.before, 1), round(self.after, 1), round(abs(self.delta), 1),
            float(self.add.mana_value), float(self.cut.mana_value),
            round(self.cut.role_supply, 1), float(self.cut.role_target),
            round(self.cut.oversupply, 1), round(self.cut.within_role, 1),
        }
        for value in (*self.add.functions.values(), *self.cut.functions.values()):
            nums.add(round(value, 1))
        for reading in (self.kill_turn_before, self.kill_turn_after):
            if reading is not None:
                nums.add(round(reading, 1))
        if self.kill_turn_delta is not None:
            nums.add(round(abs(self.kill_turn_delta), 1))
        for rate in (self.kill_rate_before, self.kill_rate_after):
            if rate is not None:
                nums.add(round(rate * 100))
        if self.kill_rate_before is not None and self.kill_rate_after is not None:
            nums.add(round(abs(self.kill_rate_after - self.kill_rate_before) * 100))
        # Ranks are large and quoted verbatim when quoted at all.
        for rank in (self.add.edhrec_rank, self.cut.edhrec_rank):
            if rank is not None:
                nums.add(float(rank))
        return {float(n) for n in nums}


def _subtypes(card: Card) -> set[str]:
    """Creature subtypes, face by face — a DFC's combined line would otherwise leak the back
    face's pre-dash words into the front's subtypes (the bug `themer` shipped once)."""
    out: set[str] = set()
    for face in card.type_line.split("//"):
        if "—" in face:
            out.update(face.split("—", 1)[1].split())
    return out


def build_swap_brief(
    resolved: ResolvedDeck,
    add: Card,
    cut: Card,
    *,
    axis: str,
    axis_label: str,
    before: float,
    after: float,
    noise_floor: float,
    themes: Sequence[str] = (),
    wants=None,
    baseline_report=None,
    swap_report=None,
) -> SwapBrief:
    """Assemble the claim budget for one measured swap.

    `themes` are the deck's own archetypes, threaded exactly as `advise` threads them, so the
    cut's `role_target` is the one the cut was actually chosen against. Passing a different
    set here would describe a decision that was never made.
    """
    targets = redundancy.targets_for(themes)
    supply = redundancy.role_supply(resolved)
    score = redundancy.score_card(cut, supply, targets)

    subs = _subtypes(add)
    tribes = getattr(wants, "tribes", set()) or set()
    on_tribe = next(iter(subs & tribes), None) if tribes else None

    add_brief = AddBrief(
        name=add.name,
        mana_value=add.mana_value,
        type_line=add.type_line,
        functions=card_functions(tags.analyze(add)),
        edhrec_rank=add.edhrec_rank,
        on_tribe=on_tribe,
        commander_can_cheat=bool(getattr(wants, "cheats_creatures", False)),
    )
    cut_brief = CutBrief(
        name=cut.name,
        mana_value=cut.mana_value,
        type_line=cut.type_line,
        functions=card_functions(tags.analyze(cut)),
        edhrec_rank=cut.edhrec_rank,
        role=score.role,
        role_supply=round(supply.get(score.role, 0.0), 1) if score.role else 0.0,
        role_target=int(targets.get(score.role, 0)) if score.role else 0,
        oversupply=round(score.oversupply, 1),
        within_role=round(score.within_role, 2),
        protected=score.protected,
        redundancy_backed=score.oversupply > 0.0,
    )
    commander = resolved.commanders[0].name if resolved.commanders else None
    return SwapBrief(
        axis=axis,
        axis_label=axis_label,
        before=round(before, 1),
        after=round(after, 1),
        delta=round(after - before, 1),
        noise_floor=round(noise_floor, 2),
        commander=commander,
        archetypes=list(themes),
        add=add_brief,
        cut=cut_brief,
        kill_turn_before=getattr(baseline_report, "avg_kill_turn", None),
        kill_turn_after=getattr(swap_report, "avg_kill_turn", None),
        kill_rate_before=getattr(baseline_report, "goldfish_kill_rate", None),
        kill_rate_after=getattr(swap_report, "goldfish_kill_rate", None),
        # The ONLY card names a faithful sentence may contain. Everything else in the deck is
        # a fabrication risk: a model that reaches for a plausible-sounding synergy piece the
        # deck does not run has invented a card into someone's decklist.
        allowed_card_names=[n for n in (add.name, cut.name, commander) if n],
    )
