"""Per-bracket reference distributions for the Power Profile axes (plan E1).

Sweeps every corpus deck carrying a `# bracket: N` header through
`analyze_deck(..., run_resilience=True)`, caches one metric row per deck to JSONL
(resumable), and bakes per-bracket p25/p50/p75 (+ n, none_count, thin) for every
`advisor.AXES` axis, the pod score, avg_kill_turn and avg_commander_turn into
`src/mythgauntlet/ratings/reference.py` as BRACKET_AXIS_REFERENCE.

    python scripts/bracket_axis_reference.py --limit 5            # smoke run (prints table)
    python scripts/bracket_axis_reference.py --bake               # sweep (resumable) + bake
    python scripts/bracket_axis_reference.py --aggregate-only --bake   # re-bake from cache
    python scripts/bracket_axis_reference.py --check              # cache vs baked constant

NOT CI-SAFE: needs data/cards_slim.json and a semantics store. The cache is keyed by
(deck filename, runs), so changing --runs starts a fresh sweep.
"""

from __future__ import annotations

import argparse
import json
import pprint
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from bracket_accuracy import labelled_decks  # noqa: E402  -> list[tuple[Path, int]] (path, bracket label)
from mythgauntlet.sim.tier0 import DEFAULT_ANALYZE_TURNS  # noqa: E402

REFERENCE_PY = ROOT / "src" / "mythgauntlet" / "ratings" / "reference.py"
DEFAULT_CACHE = ROOT / ".cache" / "bracket_axis_rows.jsonl"
BEGIN_MARK = "# === BEGIN GENERATED: BRACKET_AXIS_REFERENCE ==="
END_MARK = "# === END GENERATED: BRACKET_AXIS_REFERENCE ==="
THIN_N = 20
EXTRA_METRICS = ("pod", "avg_kill_turn", "avg_commander_turn")


def compute_row(resolved, cfg, store):
    from mythgauntlet.ratings.analysis import analyze_deck
    from mythgauntlet.ratings import advisor
    a = analyze_deck(resolved, cfg, store, run_resilience=True)
    metrics = {}
    for axis in advisor.AXES:
        metrics[axis] = round(float(advisor.axis_score(a, axis)), 4)
    metrics["pod"] = round(float(a.pod.score), 4)
    metrics["avg_kill_turn"] = round(float(a.report.avg_kill_turn), 4) if a.report.avg_kill_turn is not None else None
    metrics["avg_commander_turn"] = round(float(a.report.avg_commander_turn), 4) if a.report.avg_commander_turn is not None else None
    return metrics

def load_cache(path: Path) -> dict[tuple[str, int], dict]:
    result = {}
    if not path.exists():
        return result
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)
                key = (data["deck"], data["runs"])
                result[key] = data
            except json.JSONDecodeError:
                continue
    return result

def append_cache(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")
        f.flush()

def percentile(sorted_vals: list[float], q: float) -> float:
    import math
    if not sorted_vals:
        return None
    n = len(sorted_vals)
    pos = q * (n - 1)
    lo = math.floor(pos)
    hi = min(lo + 1, n - 1)
    return round(sorted_vals[lo] + (sorted_vals[hi] - sorted_vals[lo]) * (pos - lo), 2)

def aggregate(rows: list[dict]) -> dict[int, dict[str, dict]]:
    from mythgauntlet.ratings import advisor
    METRICS = [*advisor.AXES.keys(), *EXTRA_METRICS]
    result = {}
    for bracket in range(1, 6):
        result[bracket] = {}
        for metric in METRICS:
            values = []
            none_count = 0
            for row in rows:
                if row["label"] != bracket:
                    continue
                val = row["metrics"].get(metric)
                if val is None:
                    none_count += 1
                else:
                    values.append(val)
            n = len(values)
            thin = n < THIN_N
            p25 = percentile(sorted(values), 0.25) if n > 0 else None
            p50 = percentile(sorted(values), 0.5) if n > 0 else None
            p75 = percentile(sorted(values), 0.75) if n > 0 else None
            result[bracket][metric] = {
                "p25": p25,
                "p50": p50,
                "p75": p75,
                "n": n,
                "none_count": none_count,
                "thin": thin
            }
    return result

def render_generated(table: dict[int, dict[str, dict]], *, runs: int, decks: int, date: str) -> str:
    return f"""{BEGIN_MARK}
# Generated by scripts/bracket_axis_reference.py on {date}: runs={runs}, {decks} labelled decks.
# Do not edit by hand; re-run the script (and `--check` to detect drift).
BRACKET_AXIS_REFERENCE: dict[int, dict[str, dict]] = {pprint.pformat(table, sort_dicts=False, width=100)}
{END_MARK}
"""

def bake(table, *, runs: int, decks: int, date: str) -> None:
    with REFERENCE_PY.open("r", encoding="utf-8") as f:
        content = f.read()
    start = content.find(BEGIN_MARK)
    end = content.find(END_MARK)
    if start == -1 or end == -1:
        raise SystemExit("markers not found in reference.py")
    generated = render_generated(table, runs=runs, decks=decks, date=date)
    new_content = content[:start] + generated + content[end + len(END_MARK):]
    with REFERENCE_PY.open("w", encoding="utf-8") as f:
        f.write(new_content)

def check(table) -> int:
    from mythgauntlet.ratings import reference
    if reference.BRACKET_AXIS_REFERENCE == table:
        print("BRACKET_AXIS_REFERENCE is current.")
        return 0
    print("BRACKET_AXIS_REFERENCE needs regenerating.")
    for bracket in range(1, 6):
        for metric in table[bracket]:
            baked = reference.BRACKET_AXIS_REFERENCE.get(bracket, {}).get(metric)
            new = table[bracket][metric]
            if baked != new:
                print(f"DRIFT B{bracket} {metric}: baked {baked} now {new}")
    return 1

def cached_rows(cache_path: Path, runs: int) -> list[dict]:
    """Cache rows for this run size whose deck is still a labelled corpus deck."""
    names = {p.name for p, _ in labelled_decks()}
    return [r for (deck, n), r in load_cache(cache_path).items() if n == runs and deck in names]


def sweep(args) -> list[dict]:
    from mythgauntlet.data.scryfall import load_card_db
    from mythgauntlet.model.deck import Deck, resolve
    from mythgauntlet.semantics.store import SemanticsStore
    from mythgauntlet.sim.tier0 import SimConfig
    db = load_card_db()
    store = SemanticsStore()
    cfg = SimConfig(turns=args.turns, runs=args.runs, seed=42)
    decks = labelled_decks(args.limit)
    cache = load_cache(args.cache)
    total = len(decks)
    start_time = time.time()
    for i, (path, label) in enumerate(decks, 1):
        deck_name = path.name
        key = (deck_name, args.runs)
        if key in cache:
            continue
        try:
            resolved = resolve(Deck.parse_text(path.read_text(encoding="utf-8")), db)
            if resolved.card_count < 90:
                print(f"  [{i}] {deck_name}: skipped (card_count < 90)", flush=True)
                continue
        except Exception as exc:
            print(f"  [{i}] {deck_name}: FAILED {exc}", flush=True)
            continue
        try:
            metrics = compute_row(resolved, cfg, store)
            row = {
                "deck": deck_name,
                "runs": args.runs,
                "label": label,
                "metrics": metrics
            }
            append_cache(args.cache, row)
            cache[key] = row
            if len(cache) % 10 == 0:
                elapsed = time.time() - start_time
                print(f"  {i}/{total} (elapsed {elapsed:.0f}s)", flush=True)
        except Exception as exc:
            print(f"  [{i}] {deck_name}: FAILED {exc}", flush=True)
    return [row for (deck, runs), row in cache.items() if runs == args.runs and deck in {p.name for p, _ in decks}]

def main() -> int:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace") if hasattr(sys.stdout, "reconfigure") else None
    parser = argparse.ArgumentParser(description="Generate bracket axis reference data")
    parser.add_argument("--runs", type=int, default=120)
    parser.add_argument("--turns", type=int, default=DEFAULT_ANALYZE_TURNS)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--cache", type=Path, default=DEFAULT_CACHE)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--bake", action="store_true")
    parser.add_argument("--aggregate-only", action="store_true")
    args = parser.parse_args()
    if args.check:
        rows = cached_rows(args.cache, args.runs)
        table = aggregate(rows)
        return check(table)
    if args.aggregate_only:
        rows = cached_rows(args.cache, args.runs)
        table = aggregate(rows)
        if args.bake:
            date = time.strftime("%Y-%m-%d")
            decks = len(rows)
            bake(table, runs=args.runs, decks=decks, date=date)
        else:
            for bracket in range(1, 6):
                for metric in table[bracket]:
                    cell = table[bracket][metric]
                    thin = "thin" if cell["thin"] else ""
                    print(f"B{bracket} {metric:<20} n={cell['n']} p25={cell['p25']} p50={cell['p50']} p75={cell['p75']} none={cell['none_count']} {thin}")
        return 0
    rows = sweep(args)
    table = aggregate(rows)
    date = time.strftime("%Y-%m-%d")
    decks = len(rows)
    if args.bake:
        bake(table, runs=args.runs, decks=decks, date=date)
    else:
        for bracket in range(1, 6):
            for metric in table[bracket]:
                cell = table[bracket][metric]
                thin = "thin" if cell["thin"] else ""
                print(f"B{bracket} {metric:<20} n={cell['n']} p25={cell['p25']} p50={cell['p50']} p75={cell['p75']} none={cell['none_count']} {thin}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
